const test02Questions = [
{id:16,date:"1 Aug 2026",topic:"Energy & Environment",question:"What is the approved outlay of the Samudra Manthan — National Offshore Exploration Scheme?",options:["₹37,500 crore","₹50,000 crore","₹84,084 crore","₹1 lakh crore"],answer:2,explanation:"The Union Cabinet approved Samudra Manthan with an outlay of ₹84,084 crore through FY 2030–31.",trick:"Samudra Manthan → ₹84,084 crore.",relatedTopics:["Offshore Exploration","Energy Security","Petroleum & Natural Gas"],source:"PIB, 1 August 2026"},
  {id:17,date:"6 Aug 2026",topic:"Energy & Environment",question:"GOBARdhan approved in August 2026 is described as India's National Unified Scheme for what?",options:["Green Hydrogen","Compressed Biogas","Solar Rooftops","Offshore Wind"],answer:1,explanation:"GOBARdhan is the National Unified Scheme for Compressed Biogas and has an approved outlay of ₹23,731 crore.",trick:"GOBARdhan → Compressed Biogas (CBG).",relatedTopics:["CBG","Bioenergy","Waste to Wealth"],source:"PIB, 6 August 2026"},
  {id:18,date:"6 Aug 2026",topic:"Road Infrastructure",question:"The approved Guwahati–Tezpur Corridor project under NH-15 has a total project length of approximately:",options:["82.6 km","105.4 km","135.87 km","173 km"],answer:2,explanation:"The four-lane access-controlled Guwahati–Tezpur Corridor has a total project length of 135.871 km.",trick:"Guwahati–Tezpur Corridor → 135.87 km.",relatedTopics:["NH-15","Assam","Highways"],source:"PIB, 6 August 2026"},
  {id:19,date:"6 Aug 2026",topic:"Road Infrastructure",question:"The Guwahati–Tezpur Corridor includes an Emergency Landing Facility of approximately:",options:["2.5 km","4.9 km","7.5 km","10 km"],answer:1,explanation:"The project includes a 4.9-km Emergency Landing Facility in the Tezpur Bypass, coordinated with the IAF.",trick:"ELF → 4.9 km.",relatedTopics:["Emergency Landing Facility","IAF","NH-15"],source:"PIB, 6 August 2026"},
  {id:20,date:"9 Aug 2026",topic:"Government Schemes",question:"By August 2026, PMAY-U and PMAY-U 2.0 had sanctioned more than how many houses?",options:["75 lakh","1 crore","1.25 crore","2 crore"],answer:2,explanation:"PMAY-U reached a milestone of more than 1.25 crore houses sanctioned, with more than 1 crore completed and delivered.",trick:"PMAY-U → 1.25 crore sanctioned; 1 crore delivered.",relatedTopics:["PMAY-U","Urban Housing","MoHUA"],source:"PIB, 9 August 2026"},
  {id:21,date:"9 Aug 2026",topic:"Government Schemes",question:"Under the PMAY-U milestone reported in August 2026, more than how many houses had been completed and delivered?",options:["50 lakh","75 lakh","1 crore","1.25 crore"],answer:2,explanation:"More than 1 crore houses had been completed and delivered to beneficiaries.",trick:"PMAY-U delivered → 1 crore+.",relatedTopics:["PMAY-U","Affordable Housing","Urban Development"],source:"PIB, 9 August 2026"},
  {id:22,date:"19 Aug 2026",topic:"Railways",question:"The four railway multitracking projects approved in August 2026 increase the existing network by about:",options:["210 km","310 km","410 km","510 km"],answer:2,explanation:"The four projects across West Bengal, Odisha, Tamil Nadu and Andhra Pradesh add about 410 km.",trick:"4 projects → 410 km.",relatedTopics:["Indian Railways","Multitracking","Tamil Nadu"],source:"PIB, 19 August 2026"},
  {id:23,date:"19 Aug 2026",topic:"Railways",question:"The Gummidipundi–Gudur project approved in August 2026 involves which line work?",options:["Doubling for 147 km","3rd and 4th lines for 90 km","New line for 120 km","Electrification for 75 km"],answer:1,explanation:"The approved package includes Gummidipundi–Gudur 3rd and 4th Line for 90 km.",trick:"Gummidipundi–Gudur → 3rd & 4th line → 90 km.",relatedTopics:["Southern Railway","Andhra Pradesh","Tamil Nadu"],source:"PIB, 19 August 2026"},
  {id:24,date:"19 Aug 2026",topic:"Road Infrastructure",question:"The approved Muzaffarpur–Sitamarhi–Sonbarsa section of NH-22 in Bihar is approximately:",options:["52.6 km","72.4 km","82.578 km","102.5 km"],answer:2,explanation:"The NH-22 section is 82.578 km and is to be upgraded to four-lane standard on HAM mode.",trick:"NH-22 Bihar → 82.578 km.",relatedTopics:["NH-22","Bihar","Hybrid Annuity Mode"],source:"PIB, 19 August 2026"},
  {id:25,date:"14 Aug 2026",topic:"Railway Security",question:"Who received the President’s Medal for Distinguished Service among the RPF/RPSF personnel listed for Independence Day 2026?",options:["Rajesh Lal","Satya Prakash","C. S. Chengappa","E. Arun Moli"],answer:0,explanation:"Shri Rajesh Lal, Assistant Security Commissioner, Railway Board, received the President’s Medal for Distinguished Service.",trick:"PSM → Rajesh Lal.",relatedTopics:["RPF","RPSF","Independence Day Honours"],source:"PIB, 14 August 2026"},
  {id:26,date:"24 Aug 2026",topic:"Education",question:"How many teachers/faculty from higher education institutions and polytechnics were selected for the National Awards to Teachers 2026?",options:["15","21","25","31"],answer:1,explanation:"Twenty-one teachers/faculty from HEIs and polytechnics were selected for the National Awards to Teachers 2026.",trick:"National Awards to Teachers 2026 → 21.",relatedTopics:["National Awards to Teachers","Higher Education","Polytechnics"],source:"PIB, 24 August 2026"},
  {id:27,date:"5 Aug 2026",topic:"Railways",question:"What was the Indian Railways' 2026–27 budget grant mentioned in the August 2026 review?",options:["₹1.93 lakh crore","₹2.43 lakh crore","₹2.93 lakh crore","₹3.93 lakh crore"],answer:2,explanation:"The total 2026–27 budget grant for Indian Railways was ₹2,93,030 crore.",trick:"Railways 2026–27 grant → ₹2.93 lakh crore.",relatedTopics:["Railway Budget","Infrastructure","Railway Finance"],source:"PIB, 5 August 2026"},
  {id:28,date:"5 Aug 2026",topic:"Railway Safety",question:"By July 2026, Kavach 4.0 had been successfully commissioned on how many route kilometres according to the Railway Ministry?",options:["1,633 Rkm","2,133 Rkm","2,633 Rkm","3,633 Rkm"],answer:2,explanation:"Kavach 4.0 had been successfully commissioned on 2,633 route kilometres, including 1,423 Rkm on Delhi–Mumbai and 1,210 Rkm on Delhi–Howrah.",trick:"Kavach → 2,633 Rkm.",relatedTopics:["Kavach 4.0","Railway Safety","Automatic Train Protection"],source:"PIB, 5 August 2026"},
  {id:29,date:"5 Aug 2026",topic:"Railway Safety",question:"Kavach is India's indigenously developed system of which type?",options:["Automatic Train Protection","Automatic Fare Collection","Trackside Signalling Only","Passenger Information System"],answer:0,explanation:"Kavach is an indigenously developed Automatic Train Protection (ATP) system.",trick:"Kavach = ATP system.",relatedTopics:["Kavach","ATP","Railway Safety"],source:"PIB, 5 August 2026"},
  {id:30,date:"31 Jul 2026",topic:"Energy & Environment",question:"Samudra Manthan is a Central Sector Scheme of which Ministry?",options:["Ministry of Power","Ministry of Petroleum & Natural Gas","Ministry of Mines","Ministry of Environment"],answer:1,explanation:"Samudra Manthan is a Central Sector Scheme of the Ministry of Petroleum & Natural Gas.",trick:"Samudra Manthan → Petroleum & Natural Gas.",relatedTopics:["Hydrocarbon Exploration","Energy Security","MoPNG"],source:"PIB, 31 July 2026"}
];
