const test03Questions = [
{id:31,date:"11 Sep 2026",topic:"Digital Payments",question:"What is the main purpose of OneTag launched at Global Fintech Fest 2026?",options:["To replace all FASTags with Aadhaar","To allow NETC FASTag users to switch issuer banks without replacing the physical tag","To provide free toll travel","To convert FASTag into a credit card"],answer:1,explanation:"OneTag enables NETC FASTag users to switch issuer banks while retaining the existing physical tag.",trick:"OneTag → switch issuer bank, keep the tag.",relatedTopics:["FASTag","NETC","NPCI"],source:"PIB, 11 September 2026"},
  {id:32,date:"8–11 Sep 2026",topic:"Banking & FinTech",question:"Where was the 7th Global Fintech Fest 2026 held?",options:["Bengaluru","Mumbai","New Delhi","Hyderabad"],answer:1,explanation:"The 7th Global Fintech Fest 2026 was held in Mumbai from 8 to 11 September.",trick:"GFF 2026 → Mumbai.",relatedTopics:["FinTech","Digital Public Infrastructure","GFF"],source:"PIB, 8 September 2026"},
  {id:33,date:"8 Sep 2026",topic:"Banking & FinTech",question:"What was the theme of Global Fintech Fest 2026?",options:["Digital India for Everyone","Potential to Impact: Agentic AI, Tokenisation, Quantum - Trusted, Connected, Global Systems for Inclusive Finance","FinTech for Rural Growth","One Nation, One Payment"],answer:1,explanation:"The announced GFF 2026 theme was “Potential to Impact: Agentic AI, Tokenisation, Quantum - Trusted, Connected, Global Systems for Inclusive Finance.”",trick:"GFF 2026 → Agentic AI + Tokenisation + Quantum.",relatedTopics:["Agentic AI","Tokenisation","Quantum"],source:"PIB, 7 September 2026"},
  {id:34,date:"17–19 Sep 2026",topic:"Science & Technology",question:"The fifth edition of SEMICON India 2026 was held at:",options:["Bharat Mandapam","Yashobhoomi, New Delhi","Pragati Maidan, Mumbai","India Habitat Centre"],answer:1,explanation:"SEMICON India 2026 was held at Yashobhoomi (India International Convention and Expo Centre), New Delhi.",trick:"SEMICON India 2026 → Yashobhoomi.",relatedTopics:["Semiconductors","India Semiconductor Mission","MeitY"],source:"PIB, 18 August 2026"},
  {id:35,date:"17–19 Sep 2026",topic:"Science & Technology",question:"What was the theme of SEMICON India 2026?",options:["Silicon to Systems: Building the Ecosystem","Make Chips, Make India","Digital India 2030","Semiconductors for Viksit Bharat"],answer:0,explanation:"The fifth edition of SEMICON India 2026 was held under the theme “Silicon to Systems: Building the Ecosystem.”",trick:"SEMICON 2026 → Silicon to Systems.",relatedTopics:["Semiconductor Ecosystem","Chip Manufacturing","Semicon 2.0"],source:"PIB, 18 August 2026"},
  {id:36,date:"19 Sep 2026",topic:"Science & Technology",question:"SEMICON India 2026 concluded with participation from representatives of how many countries?",options:["32","42","52","62"],answer:2,explanation:"The event brought together representatives from 52 countries.",trick:"SEMICON 2026 → 52 countries.",relatedTopics:["Semiconductors","Global Technology","India Semiconductor Mission"],source:"PIB, 19 September 2026"},
  {id:37,date:"19 Sep 2026",topic:"Science & Technology",question:"Approximately how many exhibitors participated in SEMICON India 2026?",options:["300","450","600","800"],answer:2,explanation:"SEMICON India 2026 featured over 600 exhibitors, including around 300 international companies.",trick:"SEMICON → 600+ exhibitors.",relatedTopics:["Semiconductors","Electronics Manufacturing","R&D"],source:"PIB, 19 September 2026"},
  {id:38,date:"19 Sep 2026",topic:"Science & Technology",question:"How many MoUs, announcements and strategic initiatives were recorded during SEMICON India 2026?",options:["26","36","46","56"],answer:3,explanation:"The three-day event recorded 56 MoUs, announcements and strategic initiatives.",trick:"SEMICON 2026 → 56 MoUs/announcements/initiatives.",relatedTopics:["Semiconductors","Investment","Technology Partnerships"],source:"PIB, 19 September 2026"},
  {id:39,date:"19 Sep 2026",topic:"Government Initiatives",question:"The 20th National Rozgar Mela distributed more than how many appointment letters?",options:["25,000","40,000","51,000","75,000"],answer:2,explanation:"More than 51,000 appointment letters were distributed at the 20th Rozgar Mela.",trick:"20th Rozgar Mela → 51,000+ letters.",relatedTopics:["Rozgar Mela","Government Recruitment","Youth Employment"],source:"PIB, 19 September 2026"},
  {id:40,date:"19 Sep 2026",topic:"Government Initiatives",question:"The 20th Rozgar Mela was organised at how many locations across the country?",options:["25","35","45","55"],answer:2,explanation:"The 20th Rozgar Mela was held at 45 locations across the country.",trick:"Rozgar Mela 20th → 45 locations.",relatedTopics:["Employment","Government Recruitment","Youth"],source:"PIB, 18 September 2026"},
  {id:41,date:"19 Sep 2026",topic:"Government Initiatives",question:"With the 20th Rozgar Mela, approximately how many appointment letters had been distributed across the 20 editions?",options:["7.75 lakh","10.25 lakh","12.75 lakh","15.75 lakh"],answer:2,explanation:"The 20th edition took the cumulative number of appointment letters to about 12.75 lakh.",trick:"20 editions → 12.75 lakh+ appointments.",relatedTopics:["Rozgar Mela","Government Jobs","Youth Employment"],source:"PIB, 19 September 2026"},
  {id:42,date:"9 Sep 2026",topic:"Nutrition & Welfare",question:"What is the theme of the 9th Rashtriya Poshan Maah 2026?",options:["Poshan Se Pragati","Hamari Anganwadi Hamari Jimmedari","Swasth Bharat 2047","Nutrition for New India"],answer:1,explanation:"The 9th Rashtriya Poshan Maah 2026 carries the theme “Hamari Anganwadi, Hamari Jimmedari.”",trick:"Poshan Maah 2026 → Hamari Anganwadi Hamari Jimmedari.",relatedTopics:["POSHAN Abhiyaan","Anganwadi","Nutrition"],source:"PIB, 7–9 September 2026"},
  {id:43,date:"9 Sep 2026",topic:"Nutrition & Welfare",question:"Where was the 9th Rashtriya Poshan Maah 2026 launched?",options:["Lucknow","Varanasi","New Delhi","Bhopal"],answer:1,explanation:"The campaign was launched at the Rudraksh International Cooperation and Convention Centre in Varanasi, Uttar Pradesh.",trick:"Poshan Maah launch → Varanasi.",relatedTopics:["Anganwadi","Mission Poshan 2.0","Women & Child Development"],source:"PIB, 9 September 2026"},
  {id:44,date:"1 Sep 2026",topic:"Education",question:"The extended last date for NMMSS 2026–27 scholarship applications on the National Scholarship Portal is:",options:["15 Sep 2026","30 Sep 2026","15 Oct 2026","31 Oct 2026"],answer:1,explanation:"The Ministry of Education extended the last date for submission of NMMSS 2026–27 applications to 30 September 2026.",trick:"NMMSS application → 30 September 2026.",relatedTopics:["NMMSS","National Scholarship Portal","School Education"],source:"PIB, 1 September 2026"},
  {id:45,date:"19 Sep 2026",topic:"Energy & Consumer Services",question:"From which date will biometric Aadhaar authentication be mandatory for subsidised domestic LPG refills?",options:["1 September 2026","15 September 2026","1 October 2026","1 January 2027"],answer:2,explanation:"From 1 October 2026, domestic LPG consumers must have completed biometric Aadhaar authentication to book subsidised refills at the regulated price.",trick:"Subsidised LPG + BAA → 1 October 2026.",relatedTopics:["LPG Subsidy","Aadhaar Authentication","Petroleum"],source:"PIB, 19 September 2026"}
];
