const test04Questions = [
{id:46,date:"18 Sep 2026",topic:"Environment",question:"What is the theme of Swachhata Hi Seva 2026?",options:["Swachh Bharat, Swasth Bharat","Swachhata Mein Sahbhag; Swachh Bharat, Viksit Bharat","Clean India, Green India","Swachhata Se Samriddhi"],answer:1,explanation:"Swachhata Hi Seva 2026 is being observed under the theme “Swachhata Mein Sahbhag; Swachh Bharat, Viksit Bharat.”",trick:"SHS 2026 → Swachhata Mein Sahbhag.",relatedTopics:["Swachhata Hi Seva","Swachh Bharat Mission","Solid Waste Management"],source:"PIB, 18 September 2026"},
  {id:47,date:"18 Sep 2026",topic:"Environment",question:"Swachhata Hi Seva 2026 is being observed from which period?",options:["1 September to 30 September 2026","17 September to 2 October 2026","17 September to 17 October 2026","2 October to 31 October 2026"],answer:1,explanation:"The SHS 2026 campaign is currently running from 17 September to 2 October 2026.",trick:"SHS 2026 → 17 Sep to 2 Oct.",relatedTopics:["Swachhata Hi Seva","Jan Bhagidari","Sanitation"],source:"PIB, 18 September 2026"},
  {id:48,date:"20 Sep 2026",topic:"Rural Development",question:"According to the PIB backgrounder on last-mile rural transformation, approximately how many Community Resource Persons (CRPs) are working across the country?",options:["3 lakh","6 lakh","9 lakh","12 lakh"],answer:2,explanation:"The backgrounder states that more than 9 lakh Community Resource Persons form a grassroots service-delivery network.",trick:"CRPs → 9 lakh+.",relatedTopics:["Community Resource Persons","Rural Development","Self Help Groups"],source:"PIB, 20 September 2026"},
  {id:49,date:"20 Sep 2026",topic:"Health & Nutrition",question:"The PIB backgrounder on last-mile rural transformation states that over how many ASHAs are strengthening community healthcare?",options:["5.40 lakh","8.40 lakh","10.40 lakh","15.40 lakh"],answer:2,explanation:"The backgrounder reports over 10.40 lakh ASHAs supporting community healthcare and early childhood services.",trick:"ASHAs → 10.40 lakh+.",relatedTopics:["ASHAs","Primary Healthcare","Rural Health"],source:"PIB, 20 September 2026"},
  {id:50,date:"19 Sep 2026",topic:"Employment",question:"The 20th National Rozgar Mela distributed more than how many appointment letters?",options:["31,000","41,000","51,000","61,000"],answer:2,explanation:"More than 51,000 appointment letters were distributed to newly appointed youth at the 20th Rozgar Mela.",trick:"20th Rozgar Mela → 51,000+ appointment letters.",relatedTopics:["Rozgar Mela","Government Recruitment","Youth Employment"],source:"PIB, 19 September 2026"},
  {id:51,date:"20 Sep 2026",topic:"Awards & Honours",question:"The 72nd National Film Awards announced in 2026 honour achievements in Indian cinema for which year?",options:["2022","2023","2024","2025"],answer:2,explanation:"The 72nd National Film Awards honour achievements in Indian cinema for the year 2024.",trick:"72nd National Film Awards → 2024 cinema achievements.",relatedTopics:["National Film Awards","Indian Cinema","Ministry of Information & Broadcasting"],source:"PIB, 20 September 2026"},
  {id:52,date:"20 Sep 2026",topic:"Awards & Honours",question:"Where is the 72nd National Film Awards ceremony scheduled to be held on 22 September 2026?",options:["New Delhi","Mumbai","Ekta Nagar, Gujarat","Hyderabad"],answer:2,explanation:"The President of India is scheduled to present the 72nd National Film Awards on 22 September 2026 at Ekta Nagar, Gujarat.",trick:"72nd NFA ceremony → Ekta Nagar, Gujarat.",relatedTopics:["National Film Awards","Ekta Nagar","Cinema Awards"],source:"PIB, 20 September 2026"},
  {id:53,date:"16 Sep 2026",topic:"Awards & Honours",question:"Who is to receive the Dadasaheb Phalke Award for the year 2024?",options:["Amitabh Bachchan","Anant Nag","Naseeruddin Shah","Mohanlal"],answer:1,explanation:"The Government of India announced the Dadasaheb Phalke Award for 2024 for veteran actor Anant Nag.",trick:"Dadasaheb Phalke Award 2024 → Anant Nag.",relatedTopics:["Dadasaheb Phalke Award","National Film Awards","Indian Cinema"],source:"PIB, 16 September 2026"},
  {id:54,date:"17 Sep 2026",topic:"Science & Technology",question:"What is the approved outlay of Semicon 2.0?",options:["₹76,000 crore","₹1,00,000 crore","₹1,27,500 crore","₹1,50,000 crore"],answer:2,explanation:"The Union Cabinet approved Semicon 2.0 on 15 July 2026 with an outlay of ₹1,27,500 crore.",trick:"Semicon 2.0 → ₹1,27,500 crore.",relatedTopics:["Semicon 2.0","India Semiconductor Mission","Semiconductor Manufacturing"],source:"PIB, 17 September 2026"},
  {id:55,date:"17 Sep 2026",topic:"Science & Technology",question:"Which of the following is NOT listed among the six strategic pillars of Semicon 2.0?",options:["Research and development","Chip design","Talent development","Textile manufacturing"],answer:3,explanation:"The six pillars include R&D, chip design, machines and materials, more fabs, talent development and strengthening the ATMP/OSAT industry. Textile manufacturing is not one of them.",trick:"Semicon 2.0 → R&D + Design + Equipment/Materials + Fabs + Talent + ATMP/OSAT.",relatedTopics:["Semicon 2.0","ATMP","OSAT"],source:"PIB, 17 September 2026"},
  {id:56,date:"17 Sep 2026",topic:"Economy & Industry",question:"The Union Budget 2026–27 increased the outlay of the Electronics Components Manufacturing Scheme (ECMS) to:",options:["₹22,000 crore","₹30,000 crore","₹40,000 crore","₹50,000 crore"],answer:2,explanation:"Budget 2026–27 increased the ECMS outlay to ₹40,000 crore.",trick:"ECMS → ₹40,000 crore.",relatedTopics:["ECMS","Electronics Manufacturing","Make in India"],source:"PIB, 3 February 2026; PIB, 17 September 2026"},
  {id:57,date:"17 Aug 2026",topic:"Economy & Industry",question:"As of August 2026, how many ECMS projects had been approved across 15 states?",options:["76","86","96","106"],answer:3,explanation:"As of August 2026, 106 ECMS projects had been approved across 15 states, involving an approved investment of ₹69,548 crore.",trick:"ECMS August 2026 → 106 projects, 15 states.",relatedTopics:["ECMS","Electronics Components","Industrial Investment"],source:"PIB, 17 August 2026"},
  {id:58,date:"17 Sep 2026",topic:"Mining & Infrastructure",question:"In which year was the Pradhan Mantri Khanij Kshetra Kalyan Yojana (PMKKKY) launched?",options:["2014","2015","2016","2017"],answer:1,explanation:"PMKKKY was launched on 17 September 2015 and directs District Mineral Foundation funds toward welfare and development in mining-affected areas.",trick:"PMKKKY → 17 September 2015.",relatedTopics:["PMKKKY","District Mineral Foundation","Mining-Affected Areas"],source:"PIB, 17 September 2026"},
  {id:59,date:"19 Sep 2026",topic:"Railway Safety",question:"Indian Railways approved ₹252 crore for Kavach 4.0 on how many route kilometres of the Lucknow Division?",options:["407.7 RKM","507.7 RKM","607.7 RKM","707.7 RKM"],answer:2,explanation:"Indian Railways approved ₹252 crore for Kavach 4.0 on 607.7 route kilometres of the Lucknow Division.",trick:"Lucknow Division → Kavach 4.0 → 607.7 RKM → ₹252 crore.",relatedTopics:["Kavach 4.0","Lucknow Division","Railway Safety"],source:"PIB, 19 September 2026"},
  {id:60,date:"18 Sep 2026",topic:"Railways",question:"The new rail line approved between Mukutban (Adilabad) and Gadchandur is approximately:",options:["28.21 km","38.21 km","48.21 km","58.21 km"],answer:1,explanation:"Indian Railways approved a 38.21-km new rail line between Mukutban (Adilabad) and Gadchandur at a cost of ₹493 crore.",trick:"Mukutban–Gadchandur → 38.21 km.",relatedTopics:["Indian Railways","New Rail Lines","Maharashtra-Telangana Connectivity"],source:"PIB, 18 September 2026"}
];
